# Screen-like prefix (Ctrl‑a)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload config quickly
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Added built in support OSC 52 support
set-option -g set-clipboard on

# Better splits: unbind defaults, bind h/v
unbind '"'
unbind %
bind h split-window -v
bind v split-window -h

# Start numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# 256-colors
set -g default-terminal "screen-256color"

# Disallow Renaming
set -g allow-rename off

# TPM and plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-yank'

# Prefix‑highlight styling (must come before run)
set -g @prefix_highlight_fg 'colour10'
set -g @prefix_highlight_bg 'colour0'
set -g @prefix_highlight_prefix_prompt 'PREFIX'
set -g @prefix_highlight_show_copy_mode 'on'

set -g @override_copy_command "xclip -selection clipboard -i"
set -g @yank_selection 'clipboard'
set -g @yank_action 'copy-pipe-and-cancel'

#Adding Mouse support

set -g mouse on
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# TMUX Plugin Manager init (keep at bottom)
run-shell '~/.tmux/plugins/tpm/tpm'

# Vi-style copy mode
setw -g mode-keys vi

